### ISSUE TITLE
Lua Bindings

### ISSUE THREAD

**Issue by kyle-emmerich** [kyle-emmerich/blueshift-engine#15]
Gotta bind it all!

Math library:
- [x] Vector4
- [x] Matrix4
- [x] Quaternion
- [ ] ColorRGBA8
- [ ] Coordinate
- [ ] Ray

Core:
- [ ] Engine
- [ ] ConfigFile
- [ ] Timer
- [ ] Event
- [ ] Exceptions(?)
- [ ] UUID
- [ ] DebugConsole(?)

Scene graph:
- [ ] SceneGraph
- [ ] Object
- [ ] CameraComponent
- [ ] MeshComponent
- [ ] ScriptableComponent

Physics:
- [ ] TBD

Graphics:
- [ ] TBD

Input:
- [ ] TBD

Platform:
- [ ] TBD

**Comment by Bosswalrus** [comment]
Wooo
